AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: SAM Template
Globals:
  Function:
    Timeout: 30
Resources:
  emailAuth:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: emailAuth_Stack/template.yaml
