AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: SAM Template
Globals:
  Function:
    Timeout: 30
Resources:
  s3_lambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: s3_lambda
      CodeUri: s3_lambda/
      Runtime: nodejs14.x
      Environment:
        Variables:
          userinfoTable:
            Ref: UserTabel
      Policies:
        - AWSLambdaDynamoDBExecutionRole
        - DynamoDBCrudPolicy:
            TableName:
              Ref: UserTabel
      Handler: app.lambdaHandler
